<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CrmKanban.Application\CrmKanban.Application.csproj" />
    <ProjectReference Include="..\CrmKanban.Domain\CrmKanban.Domain.csproj" />
  </ItemGroup>
</Project>
